### ISSUE TITLE
Getting 'AttributeError' in pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py (RM #1464)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#432]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/1464***
*Originally created by **navnath gadakh** at 2016-07-18 10:09:04 UTC.*

When I run testsuite with python3.4 I get attribute error (It's working fine with python2.7)
Detailed traceback is below
File "/home/edb/Navnath/pgadmin4/web/pgadmin/browser/server_groups/servers/__init__.py", line 359, in delete
    info = traceback.format_exc()
  File "/usr/lib/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'

**Comment by dpage** [comment]
Issue closed on Redmine.
