### ISSUE TITLE
dev-db/pgadmin4-4.16 does not compile with python3.8 (RM #5106)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3254]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5106***
*Originally created by **Pavol Cupka** at 2020-01-20 19:58:27 UTC.*

This is on gentoo like os trying to compile pgadmin4 from source with python-3.8 as the main interpreter. 

<pre><code class="text">
x86_64-pc-linux-gnu-g++ -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -L/usr/lib64 -lcrypt -lpthread -ldl -lutil -lm -lm -o pgAdmin4 pgAdmin4.o Server.o ConfigWindow.o TrayIcon.o LogWindow.o MenuActions.o FloatingWindow.o Logger.o qrc_pgAdmin4.o moc_Server.o moc_ConfigWindow.o moc_TrayIcon.o moc_LogWindow.o moc_MenuActions.o moc_FloatingWindow.o   -lcrypt -ldl -lutil -lm /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Core.so -lGL -lpthread   
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libQt5Network.so: warning: EVP_CipherFinal is often misused, please use EVP_CipherFinal_ex and EVP_CIPHER_CTX_cleanup
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.o: in function `Server::~Server()':
Server.cpp:(.text+0x2e9): undefined reference to `Py_Finalize'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.o: in function `Server::run()':
Server.cpp:(.text+0x64d): undefined reference to `PyRun_SimpleStringFlags'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x6fe): undefined reference to `PyRun_SimpleStringFlags'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x798): undefined reference to `PyRun_SimpleStringFlags'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x872): undefined reference to `PySys_SetArgv'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x8fb): undefined reference to `PyRun_SimpleFileExFlags'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.o: in function `Server::Server(unsigned short, QString, QString)':
Server.cpp:(.text+0xf75): undefined reference to `Py_NoSiteFlag'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0xf99): undefined reference to `Py_NoUserSiteDirectory'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0xfa6): undefined reference to `Py_DontWriteBytecodeFlag'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1065): undefined reference to `Py_SetProgramName'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1c1d): undefined reference to `Py_SetPythonHome'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1c6f): undefined reference to `Py_Initialize'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1cc8): undefined reference to `PySys_GetObject'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1d85): undefined reference to `PyUnicode_DecodeFSDefault'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1d94): undefined reference to `PyList_Append'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1f31): undefined reference to `PyImport_ImportModule'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x1fe3): undefined reference to `PyFile_FromFd'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: Server.cpp:(.text+0x2033): undefined reference to `PyObject_SetAttrString'
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: pgAdmin4] Error 1
 * ERROR: dev-db/pgadmin4-4.16::nokit failed (compile phase):

</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
