### ISSUE TITLE
Debugger does not work on python 2.7 (RM #4419)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2717]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4419***
*Originally created by **Alex Kim** at 2019-07-01 17:07:05 UTC.*

The debugger works when switching over to python3.

Whenever I try to use the debugger on pgadmin4, I either get a (TypeError: 'NoneType' object does not support item assignment) if I try to debug directly or (TypeError: 'NoneType' object has no attribute '__getitem__') when i try to set a breakpoint.

I have attached a screenshot of the stacktrace and some of the functions involved and the text of the TraceBacks. Any and all help would be greatly appreciated.

PgAdmin 4.4.9
Mac OS X 10.4.5
PgAdmin 10.9.2 / 11. 4. 2
Python 2.7

NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ak/Desktop/pgadmin4/web/pgadmin/tools/debugger/__init__.py", line 768, in initialize_target
    'function_name': de_inst.function_data['name'],
TypeError: 'NoneType' object has no attribute '__getitem__'

'NoneType' object does not support item assignment
Traceback (most recent call last):
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ak/.virtualenvs/pgadmin4/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ak/Desktop/pgadmin4/web/pgadmin/tools/debugger/__init__.py", line 756, in initialize_target
    de_inst.function_data['args_value'] = data
TypeError: 'NoneType' object does not support item assignment

**Comment by dpage** [comment]
Issue closed on Redmine.
