### ISSUE TITLE
Can't modify a string after upgrade to 4.9  (RM #4426)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#2723]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4426***
*Originally created by **Andrei Levin** at 2019-07-02 15:50:51 UTC.*

When I try to modify a value the Data Output disappears and compare a message: "'int' object has no attribute 'replace'". It works without problem with previous version

**Comment by dpage** [comment]
Issue closed on Redmine.
