### ISSUE TITLE
pgAdmin4 fails to start after upgrade to 4.21 (RM #5531)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3582]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5531***
*Originally created by **Joel Williamson** at 2020-05-15 21:27:48 UTC.*

I just updated pgAdmin4 from version 4.18 to 4.21.  At the same time, python3-passlib was upgraded from 1.6.5-4 to 1.7.1-1, and python-flask-security was updated from 1.7.5-2 to 3.4.2-1.  After the upgrade, pgAdmin will not start, with the status message changing from "Starting pgAdmin4 server..." to "Taking longer than usual..." to "Almost there...", and finally going away to be replaced with a "Fatal Error" with message "The application server could not be contacted."

The log file pgadmin4.log contains several of these exception reports:

AttributeError: 'Request' object has no attribute 'is_json'
2020-05-15 17:21:36,726: ERROR	pgadmin:	'Request' object has no attribute 'is_json'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/usr/lib/python3/dist-packages/flask_principal.py", line 477, in _on_before_request
    identity = loader()
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 515, in _identity_loader
    if not isinstance(current_user._get_current_object(), AnonymousUserMixin):
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 302, in _get_user
    current_app.login_manager._load_user()
  File "/usr/lib/python3/dist-packages/flask_login/login_manager.py", line 313, in _load_user
    return self._load_from_request(request)
  File "/usr/lib/python3/dist-packages/flask_login/login_manager.py", line 370, in _load_from_request
    user = self.request_callback(request)
  File "/usr/lib/python3/dist-packages/flask_security/core.py", line 475, in _request_loader
    if request.is_json:
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)

I believe this is the same situation reported in Bugs 5524 & 5527.  In those bugs the "pip3 freeze" output was requested, so here's mine:

acme==0.31.0
alembic==0.8.2.dev0
apt-clone==0.2.1
apt-xapian-index==0.47
apturl==0.5.2
asn1crypto==0.22.0
Babel==1.3
blinker==1.3
Brlapi==0.6.4
certbot==0.31.0
certbot-apache==0.31.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
command-not-found==0.3
ConfigArgParse==0.11.0
configobj==5.0.6
cryptography==2.8
defer==1.0.6
dirspec==13.10
ecdsa==0.13
Flask==0.10.1
Flask-BabelEx==0.9.3
Flask-Compress==1.4.0
Flask-Gravatar==0.4.2
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Migrate==1.7.0
Flask-Paranoid==0.2.0
Flask-Principal==0.4.0
Flask-Script==0.6.7
Flask-Security-Too==3.4.2
Flask-SQLAlchemy==1.0
Flask-WTF==0.14.2
funcsigs==0.4
future==0.18.2
httplib2==0.9.1
idna==2.5
itsdangerous==0.24
Jinja2==2.8
josepy==1.1.0
ldap3==1.0.3
louis==2.6.4
lxml==3.5.0
Mako==1.0.3
MarkupSafe==0.23
mock==1.3.0
ndg-httpsclient==0.4.2
oauthlib==1.0.3
onboard==1.2.0
oneconf==0.3.9
paramiko==1.16.0
parsedatetime==2.4
passlib==1.7.1
pbr==1.8.0
pexpect==4.0.1
Pillow==3.1.2
piston-mini-client==0.7.5
psutil==5.0.1
psycopg2==2.8.5
ptyprocess==0.5
pyasn1==0.1.9
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0
pygobject==3.20.0
PyICU==1.9.2
PyJWT==1.3.0
pyOpenSSL==17.3.0
pyRFC3339==1.0
python-apt==1.1.0b1+ubuntu0.16.4.8
python-augeas==0.5.0
python-dateutil==2.4.2
python-debian==0.1.27
python-telegram-bot==12.2.0
python-xapp==1.0.0
pytz==2014.10
pyxdg==0.25
reportlab==3.3.0
requests==2.18.1
requests-toolbelt==0.8.0
screen-resolution-extra==0.0.0
sessioninstaller==0.0.0
setproctitle==1.1.8
simplejson==3.8.1
six==1.13.0
speaklater==1.4
SQLAlchemy==1.0.11
sqlparse==0.2.4
sshtunnel==0.1.4
system-service==0.3
thin-client-config-agent==0.8
tornado==6.0.3
ubuntu-drivers-common==0.0.0
ufw==0.35
urllib3==1.21.1
vboxapi==1.0
virtkey==0.63.0
Werkzeug==0.16.0
WTForms==2.1
xkit==0.0.0
zope.component==4.3.0
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.3.2

Note that Flask-Security-Too is present rather than Flask-Security, unlike the bug reporter for 5524.

I am eager to get pgadmin working, so if you require any additional information, I will be happy to supply it.

**Comment by dpage** [comment]
Issue closed on Redmine.
