### ISSUE TITLE
pgAdmin not starting after upgrade to 4.15 on Ubuntu (RM #5006)

### ISSUE THREAD

**Issue by dpage** [postgres/pgadmin4#3178]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5006***
*Originally created by **Tobias Scheffler** at 2019-12-11 14:43:35 UTC.*

After upgrading to version 4.15 I recived the following error:

[Wed Dec 11 09:34:53.305191 2019] [wsgi:error] [pid 29397:tid 140418449344256]  mod_wsgi (pid=29397): Exception occurred processing WSGI script '/usr/share/pgadmin4/web/pgAdmin4.wsgi'.
[Wed Dec 11 09:34:53.305844 2019] [wsgi:error] [pid 29397:tid 140418449344256] Traceback (most recent call last):
[Wed Dec 11 09:34:53.305871 2019] [wsgi:error] [pid 29397:tid 140418449344256]   File "/usr/lib/python3/dist-packages/flask/app.py", line 1997, in __call__
[Wed Dec 11 09:34:53.305879 2019] [wsgi:error] [pid 29397:tid 140418449344256]    return self.wsgi_app(environ, start_response)
[Wed Dec 11 09:34:53.305885 2019] [wsgi:error] [pid 29397:tid 140418449344256]  File "/usr/share/pgadmin4/web/pgAdmin4.py", line 95, in __call__
[Wed Dec 11 09:34:53.305889 2019] [wsgi:error] [pid 29397:tid 140418449344256]      return self.app(environ, start_response)
[Wed Dec 11 09:34:53.305904 2019] [wsgi:error] [pid 29397:tid 140418449344256] AttributeError: 'ReverseProxied' object has no attribute 'app'
[Wed Dec 11 09:34:59.161435 2019] [wsgi:error] [pid 29397:tid 140418491307776] mod_wsgi (pid=29397): Exception occurred processing WSGI script '/usr/share/pgadmin4/web/pgAdmin4.wsgi'.

The problem is that "app" is not initialized as it was in the version before:

How it is in v4.15
<pre><code class="python">
class ReverseProxied(object):
    def __init__(self, app):
        # https://werkzeug.palletsprojects.com/en/0.15.x/middleware/proxy_fix/#module-werkzeug.middleware.proxy_fix
        try:
            from werkzeug.middleware.proxy_fix import ProxyFix
            self.app = ProxyFix(app,
                                x_for=config.PROXY_X_FOR_COUNT,
                                x_proto=config.PROXY_X_PROTO_COUNT,
                                x_host=config.PROXY_X_HOST_COUNT,
                                x_port=config.PROXY_X_PORT_COUNT,
                                x_prefix=config.PROXY_X_PREFIX_COUNT
                                )
     except ImportError:
            pass
</code></pre>

I added the initialisation of the app to fix this (like it was in v4.13):

<pre><code class="python">
        except ImportError:
            self.app = app
</code></pre>

**Comment by dpage** [comment]
Issue closed on Redmine.
